#!perl

use strict;
use warnings FATAL => 'all';

use Test::More tests => 6;    # last test to print
use LWP::UserAgent;

my %args = (
    max_redirect => 0,
    agent        =>
'Mozilla/5.0 (Macintosh; U; PPC Mac OS X Mach-O; en-US; rv:1.8.0.2) Gecko/20060308 Firefox/1.5.0.2'
);
use LWP::Protocol::http;      # needed for our override
$LWP::Protocol::http::sl_proxy = 1;
use WWW::Mechanize;
my $mech = WWW::Mechanize->new(%args);
my $url   = 'http://www.taperfriendlymusic.org/';
my $suffix = 'users.pl';
my $login = 'taper';
my $pass  = 'friendly';
my $query =
  "?op=userlogin&unickname=$login&upasswd=$pass&returnto=$url";

$mech->get("$url$suffix");
cmp_ok($mech->res->code, '==', 200, 'check 200 rc');
ok($mech->content =~ m/taperfriendly/, 'taperfriendly keyword');

$mech->submit_form( form_number => 3,
	fields => {
		unickname => $login,
		upasswd => $pass,
	},
	button => 'userlogin',
);

cmp_ok($mech->res->code, '==', 302, 'check redirect code');
ok($mech->res->header('set-cookie'), 'we got a cookie back');
ok($mech->res->header('location'), 'we got a location header back');
$mech->get($mech->res->header('location'));
ok($mech->res->content =~ m/this page was generated by a/i, 'logged in');


__END__
