#!/bin/bash
#
# sl_nameserver		Startup script for the Silver Lining nameserver
# chkconfig: - 99 3
# description: The SL nameserver
# processname: sl_nameserver
# config: /etc/sl/sl.conf
#
### BEGIN INIT INFO
# Provides: sl_nameserver
# Required-Start: $network
# Required-Stop: $network
# Short-Description: start and stop SL nameserver
# Description: SL Nameserver
### END INIT INFO


prog=sl_nameserver
path='/usr/local/bin'
progpath="$path/$prog"

start() {
        echo -n $"Starting $prog: "
	$progpath 2>&1 >> /var/log/$prog &
        RETVAL=$?
        echo
	return $RETVAL
}

stop() {
	echo -n $"Stopping $prog: "
	pkill "$prog"
	RETVAL=$?
	echo
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart)
	stop
	start
	;;
  status)
	ps aux | grep $prog
	;;
  *)
	echo $"Usage: $prog {start|stop|restart|status}"
	RETVAL=2
esac

exit $RETVAL
