<div id="skinny_nav">
<ul>
    <li class="help"><a href="#">Help</a></li>
    <li><a href="#">Logout</a></li>
    <li>Welcome: Alex Wolfe</li>
  </ul>
<div class="clear"></div>
</div>
<!-- END -->


<div id="masthead">
	<h1><span></span>Silver Lining Networks</h1>
	<!-- NAVIGATION -->
	<div id="navigation">  
	<ul>
	    <li><a href="#">Settings</a></li>
	    <li><a href="#">Statistics</a></li>
	    <li><a href="#">My Network</a></li>
	    <li class="selected"><a href="#">Dashboard</a></li>
	  </ul>
	<div class="clear"></div>
	</div>
	<!-- END -->

</div>