<div id="header">
	<div id="masthead">
		<h1><span></span>Silver Lining Networks</h1>
		<!-- NAVIGATION -->
		
		<ul class="one_sixth right topnav">
		    <li class="help"><a href="#">Help</a></li>
		    <li><a href="#">Logout</a></li>
		</ul>
	
	<div class="clear"></div>
	</div>
	<!-- END -->

	
	<div id="navigation">  
		<ul>
		    <li><a href="cms_settings.php">Settings</a></li>
		    <li><a href="cms_stats.php">Statistics</a></li>
		    <li><a href="cms_campaigns.php">Campaigns</a></li>
		    <li><a href="cms_network.php">My Network</a></li>
		    <li class="selected"><a href="cms_index.php">Dashboard</a></li>
		</ul>
		<div class="clear"></div>
	</div>
</div>


<div id="breadcrumb">  
<ul>
    <li><a href="#">Network</a></li>
    <li class="selected"><a href="#">Add Router</a></li>
  </ul>
<div class="clear"></div>
</div>

